@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "tim"
}
###
@accessToken = Bearer {{login.response.body.token}}

@consultationsPath = {{hostname}}/api/consultations

### patient create a consult appointment
POST {{consultationsPath}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "doctorTimeSlotId": "d86ca72e-be83-4e57-9f9e-48b9c8786b36"
}
###

### patient cancel a consult appointment
@patientCancelAppointmentId = 9a05c0da-1764-4600-88df-6eaf65d54e20
DELETE {{consultationsPath}}/{{patientCancelAppointmentId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient get consult appointments
Get {{consultationsPath}}/patient
Authorization: {{accessToken}}
Content-Type: application/json

###

### doctor get consult appointments
Get {{consultationsPath}}/doctor
Authorization: {{accessToken}}
Content-Type: application/json

###

### Doctor create a doctor time slot
POST {{consultationsPath}}/time-slot
Authorization: {{accessToken}}
Content-Type: application/json

{
  "startAt": "2023-07-29 11:30:00.090",
  "endAt": "2021-07-29 11:00:00.090"
}
### 

### Doctor edit a doctor time slot
@DoctorEditTimeSlotId = a5b909a6-9c06-49ba-b6ac-33edc6721caa
PATCH {{consultationsPath}}/time-slot/{{DoctorEditTimeSlotId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "startAt": "2023-08-22 11:10:00.09",
  "endAt": "2023-08-22 11:30:00.09"
}

### Doctor create multiple time slots
POST {{consultationsPath}}/multiple-time-slots
Authorization: {{accessToken}}
Content-Type: application/json

{ "timeSlots":
  [{
  "startAt": "2023-07-19 11:00:00.090",
  "endAt": "2023-07-19 11:30:00.090"
},
{
  "startAt": "2023-07-21 11:00:00.090",
  "endAt": "2023-07-21 11:30:00.090"
}]
}

### 