@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "Eric@gmail.com",
  "password": "Eric"
}
###
@accessToken = Bearer {{login.response.body.token}}

@consultationsPath = {{hostname}}/api/consultations

### patient create a consult appointment
POST {{consultationsPath}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "doctorTimeSlotId": "a01727cc-dd81-466c-88b5-5fdc4fce5eb3"
}
###

### patient cancel a consult appointment
@patientCancelAppointmentId = 236f61db-a9a5-486a-9572-3558860ffd52
DELETE {{consultationsPath}}/{{patientCancelAppointmentId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient get consult appointments
Get {{consultationsPath}}/patient?onlyUpComing=true&type=CLINIC
Authorization: {{accessToken}}
Content-Type: application/json

###

### doctor get consult appointments
Get {{consultationsPath}}/doctor?onlyUpComing=true&type=CLINIC
Authorization: {{accessToken}}
Content-Type: application/json

###

### Doctor create a doctor time slot
POST {{consultationsPath}}/time-slot
Authorization: {{accessToken}}
Content-Type: application/json

{
  "startAt": "2024-05-29 11:00:00.090",
  "endAt": "2024-05-29 11:30:00.090",
  "type":"ONLINE"
}
### 

### Doctor edit a doctor time slot
@editDoctorEditTimeSlotId = a3a8512c-cb4f-41e7-aad2-55f1cef8c6d9
PATCH {{consultationsPath}}/time-slot/{{editDoctorEditTimeSlotId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "startAt": "2024-05-29 12:00:00.090",
  "endAt": "2024-05-29 12:30:00.090",
  "type":"ONLINE"
}
### 

### Doctor delete a doctor time slot
@DoctorDeleteTimeSlotId =e6dda0fd-52be-4708-9299-561b3132ac4d
DELETE {{consultationsPath}}/time-slot/{{DoctorDeleteTimeSlotId}}
Authorization: {{accessToken}}
Content-Type: application/json

### 


### Doctor create multiple time slots
POST {{consultationsPath}}/multiple-time-slots
Authorization: {{accessToken}}
Content-Type: application/json

{ "timeSlots":
  [{
  "startAt": "2024-05-19 11:00:00.090",
  "endAt": "2024-05-19 11:30:00.090",
  "type":"ONLINE"
},
{
  "startAt": "2024-05-18 11:00:00.090",
  "endAt": "2024-05-18 11:30:00.090",
  "type":"ONLINE"
}]
}
### 

### get doctor time slots
@doctorId=1fc5d738-43f9-4a77-8e1d-ab4ea15b29e3
GET {{consultationsPath}}/time-slots/doctors/{{doctorId}}?startTime=2024-04-20&endTime=2024-04-30&type=ONLINE
Authorization: {{accessToken}}
Content-Type: application/json

### 