@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "tim"
}
###
@accessToken = Bearer {{login.response.body.token}}
@healthGoalsPath = {{hostname}}/api/health-goals

### create a health goal
POST {{healthGoalsPath}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a health goal
@healthGoalId=f5ae1de0-880b-422c-9577-a78a1cf83ebb
Get {{healthGoalsPath}}/{{healthGoalId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient activate a health goal
@healthGoalId=f5ae1de0-880b-422c-9577-a78a1cf83ebb
PATCH {{healthGoalsPath}}/active/{{healthGoalId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient reject a health goal
@healthGoalId=f5ae1de0-880b-422c-9577-a78a1cf83ebb
PATCH {{healthGoalsPath}}/reject/{{healthGoalId}}
Authorization: {{accessToken}}
Content-Type: application/json
###