@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "tim"
}

###
@accessToken = Bearer {{login.response.body.token}}

@notificationsPath = {{hostname}}/api/notifications

### get notificationList
GET {{notificationsPath}}?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###


### get notificationDetails
@notificationDetailId =8228ad41-639a-486f-ad67-603c73291c2c
GET {{notificationsPath}}/{{notificationDetailId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get notification hints
GET  {{notificationsPath}}/hints
Authorization: {{accessToken}}
Content-Type: application/json
###

### read all notifications
PATCH  {{notificationsPath}}/read-all
Authorization: {{accessToken}}
Content-Type: application/json
###

### delete all notifications
DELETE {{notificationsPath}}/all
Authorization: {{accessToken}}
Content-Type: application/json
###

### delete single notification
@notificationId=e40b0703-55b2-4fbb-a0eb-8d04aea153ef
DELETE {{notificationsPath}}/{{notificationId}}
Authorization: {{accessToken}}
Content-Type: application/json
###