@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "Eric@gmail.com",
  "password": "Eric"
}
###
@accessToken = Bearer {{login.response.body.token}}
@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@getQuestionId =6151ce4b-8111-4f0c-b56a-9b3909e06a36
GET {{questionsPath}}/{{getQuestionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor answer a question
@questionId=f5b3f6c4-44ae-413b-80ca-c9ee02eede2c

POST {{questionsPath}}/{{questionId}}/answers
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Eat slowly."
}
###

# ### doctor edit a answer
# @answerId = uuid
# PATCH {{questionsPath}}/answers/{{answerId}}
# Authorization: {{accessToken}}
# Content-Type: application/json

# {
#   "comment" : "new comments"
# }
###

### doctor agree with a answer of another doctor
@doctorAgreedAnswerId=9101cee2-4551-46f2-ba7c-3354b89ab856
POST {{questionsPath}}/answers/{{doctorAgreedAnswerId}}/agreements
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "comments"
}
###

### doctor edit comment in a agreement
@agreementId=b76c156f-b8b7-4045-8c27-c13dda47e506
PATCH {{questionsPath}}/answers/agreements/{{agreementId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "new comments"
}
###

### doctor cancel a answer to a question
@doctorCancelAnswerId=2d64e58f-a6fc-4f3a-8fdb-dc1873ed3c4b
DELETE {{questionsPath}}/answers/{{doctorCancelAnswerId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor cancel a agreement to an answer
@doctorCancelAgreementanswerId=6f2c1f74-3e5f-48f5-8414-15e6a3736cad
DELETE {{questionsPath}}/answers/agreements/{{doctorCancelAgreementanswerId}}
Authorization: {{accessToken}}
Content-Type: application/json
###


