@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "eric@gmail.com",
  "password": "eric"
}
###
@accessToken = Bearer {{login.response.body.token}}
@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@questionId =e34461ad-7ba0-41e8-ad9f-a48b36390374
GET {{questionsPath}}/{{questionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient create a question
POST {{questionsPath}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "I have bad sleep. What should I do?",
  "medicalSpecialty": "INTERNAL_MEDICINE"
}
###

### patient edit a single question (only the owner can edit)
@questionEditId=28bffb86-d02f-4478-9df1-daeb74e49337
PATCH {{questionsPath}}/{{questionEditId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "new content",
  "medicalSpecialty": "INTERNAL_MEDICINE"
}
###

### patient thank a doctor's answer
@answerId = b274c5fa-0b64-49f0-9227-802fd9a80460
POST {{questionsPath}}/answers/{{answerId}}/appreciations
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment": "thank content"
}
###

### patient cancel question of their own
@questionCancelId = uuid
DELETE {{questionsPath}}/{{questionCancelId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient create appreciation to an answer
@answerCreateId = uuid
POST {{questionsPath}}/answers/{{answerCreateId}}/appreciations
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Like your reply"
}
###

### patient edit appreciation content to an answer
@appreciationId = uuid
POST {{questionsPath}}/answers/appreciations/{{appreciationId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Like your reply"
}
###

### patient cancel appreciation to an answer
@cancelAppreciationId =d1f5c2b5-3237-4716-83aa-e94fc17bc882
DELETE {{questionsPath}}/answers/appreciations/{{cancelAppreciationId}}
Authorization: {{accessToken}}
Content-Type: application/json
###