@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "timtim"
}
###
@accessToken = Bearer {{login.response.body.token}}
@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}?limit=10&page=1&askerId=df5ff2e5-9d76-42ca-acfb-688267229369
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@questionId =5cc23da1-9608-4d48-8bae-3d80e629c353
GET {{questionsPath}}/{{questionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient create a question
POST {{questionsPath}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "I have bad sleep. What should I do?",
  "medicalSpecialty": "INTERNAL_MEDICINE"
}
###

### patient edit a single question (only the owner can edit)
@questionEditId=28bffb86-d02f-4478-9df1-daeb74e49337
PATCH {{questionsPath}}/{{questionEditId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "new content",
  "medicalSpecialty": "INTERNAL_MEDICINE"
}
###

### patient thank a doctor's answer
@answerId =ebdf2978-83ac-4d23-804e-a1184bc7b699
POST {{questionsPath}}/answers/{{answerId}}/appreciations
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "thank content"
}
###

### patient cancel question of their own
@questionCancelId = uuid
DELETE {{questionsPath}}/{{questionCancelId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient edit appreciation content to an answer
@id = uuid
POST {{questionsPath}}/answers/{{id}}/appreciations
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Like your reply"
}
###

### patient cancel appreciation to an answer
@answerCancelId=b274c5fa-0b64-49f0-9227-802fd9a80460
DELETE {{questionsPath}}/answers/{{answerCancelId}}/appreciations
Authorization: {{accessToken}}
Content-Type: application/json
###