@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "Amy@gmail.com",
  "password": "Amy"
}
###
@accessToken = Bearer {{login.response.body.token}}
@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@questionId = 515a551e-f321-4086-8219-ec74ada985c3
GET {{questionsPath}}/{{questionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor answer a question
@questionId=8fcc3894-296d-4308-aba8-c11af9ca435e

POST {{questionsPath}}/{{questionId}}/answers
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Drink more warm water."
}
###

# ### doctor edit a answer
# @answerId = uuid
# PATCH {{questionsPath}}/answers/{{answerId}}
# Authorization: {{accessToken}}
# Content-Type: application/json

# {
#   "comment" : "new comments"
# }
###

### doctor agree with a answer of another doctor
@doctorAgreedAnswerId=7c13b61e-2084-46de-b4ea-bc9795fb50e5
POST {{questionsPath}}/answers/{{doctorAgreedAnswerId}}/agreements
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "comments"
}
###

### doctor edit comment in a agreement
@agreementId=b76c156f-b8b7-4045-8c27-c13dda47e506
PATCH {{questionsPath}}/answers/agreements/{{agreementId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "new comments"
}
###

### doctor cancel a answer to a question
@doctorCancelAnswerId=2d64e58f-a6fc-4f3a-8fdb-dc1873ed3c4b
DELETE {{questionsPath}}/answers/{{doctorCancelAnswerId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor cancel a agreement to an answer
@doctorCancelAgreementanswerId=6f2c1f74-3e5f-48f5-8414-15e6a3736cad
DELETE {{questionsPath}}/answers/agreements/{{doctorCancelAgreementanswerId}}
Authorization: {{accessToken}}
Content-Type: application/json
###


