@hostname = http://localhost:8080

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "user1"
}
###
@accessToken = Bearer {{login.response.body.token}}

@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@questionId = uuid
GET {{questionsPath}}/{{questionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### patient create a question
POST {{questionsPath}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "question content"
}
###

### patient edit a single question (only the owner can edit)
@questionId = uuid
PATCH {{questionsPath}}/{questionId}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "question content"
}
###

### patient thank a doctor's answer
@answerId = uuid
POST {{questionsPath}}/answers/{{answerId}}/thanks
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "thank content"
}
###

### doctor answer a question
@questionId = uuid
@answerId = uuid
POST {{questionsPath}}/{{questionId}}/answers
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "thank content"
}
###

### doctor agree with a answer of another doctor
POST {{questionsPath}}/answers/{{answerId}}/agrees
Authorization: {{accessToken}}
Content-Type: application/json

###
