@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "Eric@gmail.com",
  "password": "Eric"
}
###
@accessToken = Bearer {{login.response.body.token}}
@questionsPath = {{hostname}}/api/questions

### get questions
GET {{questionsPath}}?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single question
@getQuestionId =5cc23da1-9608-4d48-8bae-3d80e629c353
GET {{questionsPath}}/{{getQuestionId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor answer a question
@questionId=53c4e62f-9806-47ba-b3fc-02f66c14e7d8

POST {{questionsPath}}/{{questionId}}/answers
Authorization: {{accessToken}}
Content-Type: application/json

{
  "content": "Do not eat too much before sleep."
}
###

# ### doctor edit a answer
# @answerId = uuid
# PATCH {{questionsPath}}/answers/{{answerId}}
# Authorization: {{accessToken}}
# Content-Type: application/json

# {
#   "comment" : "new comments"
# }
###

### doctor agree with an answer of another doctor
@doctorAgreedAnswerId=ebdf2978-83ac-4d23-804e-a1184bc7b699
POST {{questionsPath}}/answers/{{doctorAgreedAnswerId}}/agreements
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "good answer!"
}
###

### doctor edit comment in a agreement
@Id=b76c156f-b8b7-4045-8c27-c13dda47e506
PATCH {{questionsPath}}/answers/{{Id}}/agreements
Authorization: {{accessToken}}
Content-Type: application/json

{
  "comment" : "new comments"
}
###

### doctor cancel a agreement to an answer
@doctorCancelAgreementanswerId=ebdf2978-83ac-4d23-804e-a1184bc7b699
DELETE {{questionsPath}}/answers/{{doctorCancelAgreementanswerId}}/agreements
Authorization: {{accessToken}}
Content-Type: application/json
###

### doctor get an answer details
@doctorAnswerId=ebdf2978-83ac-4d23-804e-a1184bc7b699
GET {{questionsPath}}/answers/{{doctorAnswerId}}
Authorization: {{accessToken}}
Content-Type: application/json
###