@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "Ellen@gmail.com",
  "password": "Ellen"
}
###
@accessToken = Bearer {{login.response.body.token}}

@recordsPath = {{hostname}}/api/records

### create blood pressure record
POST {{recordsPath}}/blood-pressure
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodPressureDate":"2023-05-29 15:34:38.090",
  "systolicBloodPressure": 138,
  "diastolicBloodPressure": 78,
  "heartBeat":78,
  "bloodPressureNote": "no"
}
###

### create blood sugar record
POST {{recordsPath}}/blood-sugar
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodSugarDate":"2023-05-15 16:34:38.091",
  "bloodSugarValue": 80,
  "bloodSugarNote": "no"
}
###

### create glycatedHemoglobinRecord record
POST {{recordsPath}}/glycated-hemoglobin
Authorization: {{accessToken}}
Content-Type: application/json

{
  "glycatedHemoglobinDate": "2023-05-29 18:34:38.091",
  "glycatedHemoglobinValuePercent": 5
}
###

### create weight record
POST {{recordsPath}}/weight
Authorization: {{accessToken}}
Content-Type: application/json

{
  "weightDate": "2023-05-29 16:34:38.091",
  "weightValueKg": 59,
  "weightNote": "no"
}
###


### create food record
POST {{recordsPath}}/food
Authorization: {{accessToken}}
Content-Type: application/json

{
  "foodTime": "2023-05-11 00:34:38.091",
  "foodCategory": "FRUIT",
  "foodAmount": 3,
  "foodNote": "A delicious red apple"
}
###

### edit food record

@foodRecordId=bf00a253-8d32-4d3f-86f9-2144c96faeff
PATCH {{recordsPath}}/food/{{foodRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "foodTime":"1686393000",
  "foodCategory": "FRUIT",
  "foodAmount": 110,
  "foodNote": "A delicious red apple"
}
###

### edit blood pressure record
POST {{recordsPath}}/blood-pressure
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodPressureDate": "1686393000",
  "systolicBloodPressure": 150,
  "diastolicBloodPressure": 80,
  "heartBeat": 70,
  "bloodPressureNote": "nervouse"
}
###

### edit blood pressure record
@bloodPressureRecordId=7ee5ef35-91ec-4b7d-810e-d2c45df7c745
PATCH {{recordsPath}}/blood-pressure/{{bloodPressureRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodPressureDate": "1686393000",
  "systolicBloodPressure": 100,
  "diastolicBloodPressure": 80,
  "heartBeat": 70,
  "bloodPressureNote": 150
}
###

### create exercise record
POST {{recordsPath}}/exercise
Authorization: {{accessToken}}
Content-Type: application/json

{
  "exerciseDate": "2023-05-11 00:34:38.091",
  "exerciseType": "AEROBIC_EXERCISE",
  "exerciseDurationMinute": 50,
  "exerciseIntensity": "HIGH",
  "exerciseNote": "tired"  
}
###

### get a single exercise record
@exerciseRecordId = 64b7896a-fe64-4b52-a84c-ddff1d44fb9b
GET {{recordsPath}}/exercise/{{exerciseRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single glycated hemoglobin record
@glycatedHemoglobinRecordId = uuid
GET {{recordsPath}}/glycated-hemoglobin/{{glycatedHemoglobinRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single blood pressure record
@bloodPressureRecordId =b3f54074-1466-48ff-b727-d798046fa070
GET {{recordsPath}}/blood-pressure/{{bloodPressureRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single blood sugar record
@bloodSugarRecordId = uuid
GET {{recordsPath}}/bloodSugar/{{bloodSugarRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single food record
@foodRecordId = uuid
GET {{recordsPath}}/food/{{foodRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single sleep record
@sleepRecordId = uuid
GET {{recordsPath}}/sleep/{{sleepRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single weight record
@weightRecordId = 0037ae52-0391-4ecf-9165-7b93daf7e6d9
GET {{recordsPath}}/weight/{{weightRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all exercise record lists
GET {{recordsPath}}/exercise-records?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all blood pressure record lists
GET {{recordsPath}}/blood-pressure-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all blood sugar record lists
GET {{recordsPath}}/blood-sugar-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all exercise record lists
GET {{recordsPath}}/exercise-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all food record lists
GET {{recordsPath}}/food-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all glycated hemoglobin record lists
GET {{recordsPath}}/glycated-hemoglobin-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all sleep record lists
GET {{recordsPath}}/sleep-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all weight record lists
GET {{recordsPath}}/weight-records?limit=3&page=1&targetPatientId=e6b08543-8ef9-47f0-852d-5442830089da
Authorization: {{accessToken}}
Content-Type: application/json
###