@hostname = http://localhost:10000

@usersPath = {{hostname}}/api/users

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "timtim"
}
###
@accessToken = Bearer {{login.response.body.token}}

@recordsPath = {{hostname}}/api/records

### create blood pressure record
POST {{recordsPath}}/blood-pressure
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodPressureDate":"2024-08-17 00:53:38.090",
  "systolicBloodPressure": 138,
  "diastolicBloodPressure": 78,
  "heartBeat":78,
  "bloodPressureNote": "no"
}
###

### create blood sugar record
POST {{recordsPath}}/blood-sugar
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodSugarDate":"2024-05-15 16:34:38.091",
  "bloodSugarValue": 80,
  "bloodSugarNote": "no"
}
###

### create glycatedHemoglobin record
POST {{recordsPath}}/glycated-hemoglobin
Authorization: {{accessToken}}
Content-Type: application/json

{
  "glycatedHemoglobinDate": "2023-05-29 18:34:38.091",
  "glycatedHemoglobinValuePercent": 5
}
###

### create sleep record
POST {{recordsPath}}/sleep
Authorization: {{accessToken}}
Content-Type: application/json

{
  "sleepDate": "2023-06-18 13:18:00.091",
  "sleepTime": "2023-06-18 23:00:00.091",
  "wakeUpTime": "2023-06-19 08:30:00.091",
  "sleepQuality": "FAIR",
  "sleepNote": "no"
}
###

### create weight record
POST {{recordsPath}}/weight
Authorization: {{accessToken}}
Content-Type: application/json

{
  "weightDate": "2023-05-29 16:34:38.091",
  "weightValueKg": 59,
  "weightNote": "no"
}
###


### create food record
POST {{recordsPath}}/food
Authorization: {{accessToken}}
Content-Type: application/json

{
  "foodTime": "2023-05-11 00:34:38.091",
  "foodCategory": "FRUIT",
  "foodAmount": 3,
  "foodNote": "A delicious red apple"
}
###

### edit food record

@foodRecordId=bf00a253-8d32-4d3f-86f9-2144c96faeff
PATCH {{recordsPath}}/food/{{foodRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "foodTime":"1686393000",
  "foodCategory": "FRUIT",
  "foodAmount": 110,
  "foodNote": "A delicious red apple"
}
###

### edit blood pressure record
@bloodPressureRecordId=7ee5ef35-91ec-4b7d-810e-d2c45df7c745
PATCH {{recordsPath}}/blood-pressure/{{bloodPressureRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "bloodPressureDate": "1686393000",
  "systolicBloodPressure": 100,
  "diastolicBloodPressure": 80,
  "heartBeat": 70,
  "bloodPressureNote": 150
}
###

### create exercise record
POST {{recordsPath}}/exercise
Authorization: {{accessToken}}
Content-Type: application/json

{
  "exerciseDate": "2023-05-11 00:34:38.091",
  "exerciseType": "AEROBIC_EXERCISE",
  "exerciseDurationMinute": 50,
  "exerciseIntensity": "HIGH",
  "exerciseNote": "tired"  
}
###

### get a single exercise record
@exerciseRecordId =447a687c-c6f7-4a4a-9a17-1f5b9271f88e
GET {{recordsPath}}/exercise/{{exerciseRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single glycated hemoglobin record
@glycatedHemoglobinRecordId = uuid
GET {{recordsPath}}/glycated-hemoglobin/{{glycatedHemoglobinRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single blood pressure record
@bloodPressureRecordId =c150ac1d-56d3-4a08-b680-905a768a3c88
GET {{recordsPath}}/blood-pressure/{{bloodPressureRecordId}}?targetPatientId=79ed933e-22c2-4e9a-bf71-16086f54f3f2
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single blood sugar record
@bloodSugarRecordId = uuid
GET {{recordsPath}}/bloodSugar/{{bloodSugarRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single food record
@foodRecordId = uuid
GET {{recordsPath}}/food/{{foodRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single sleep record
@sleepRecordId = uuid
GET {{recordsPath}}/sleep/{{sleepRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get a single weight record
@weightRecordId = 0037ae52-0391-4ecf-9165-7b93daf7e6d9
GET {{recordsPath}}/weight/{{weightRecordId}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all exercise record lists
GET {{recordsPath}}/exercise?limit=3&page=1
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all blood pressure record lists
GET {{recordsPath}}/blood-pressure?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-03-01&endDate=2024-03-31
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all blood sugar record lists
GET {{recordsPath}}/blood-sugar?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all exercise record lists
GET {{recordsPath}}/exercise?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all food record lists
GET {{recordsPath}}/food?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all glycated hemoglobin record lists
GET {{recordsPath}}/glycated-hemoglobin?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all sleep record lists
GET {{recordsPath}}/sleep?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Content-Type: application/json
###

### get all weight record lists
GET {{recordsPath}}/weight?limit=3&page=1&targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369&startDate=2024-02-01&endDate=2024-02-29
Authorization: {{accessToken}}
Content-Type: application/json
###

### get goal duration records
@goalId =a742ca7c-9351-42ba-a7f2-1ee67f2f0c90
GET {{recordsPath}}/goal/{{goalId}}?targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369
Authorization: {{accessToken}}
Content-Type: application/json
###