@hostname = http://localhost:7000

@usersPath = {{hostname}}/api/users

### Register new user
POST {{usersPath}}
Content-Type: application/json

{
  "displayName":"doctor2",
  "email": "doctor2@gmail.com",
  "password": "doctor2",
  "role": "DOCTOR"
}
###

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "tim"
}
###
@accessToken = Bearer {{login.response.body.token}}

### get user
GET {{usersPath}}/me
Authorization: {{accessToken}}
Content-Type: application/json
###

@patientPath = {{hostname}}/api/patients

### Register new patient
POST {{patientPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": null,
  "firstName": "Tim",
  "lastName": "Wang",
  "birthDate": "1995-12-31T00:00:00.000Z",
  "gender": "MALE",
  "medicalHistory": [
    {
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "allergy": {
    "medicine": "Penicillin",
    "food": null,
    "other": null
  },
  "familyHistory": [
    {
      "relationship": "Father",
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "relationship": "Mother",
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "heightValueCm": 180,
  "medicinceUsage": [
    {
      "medicineName": "Aspirin",
      "medicineDosage": 100,
      "medicineUnit": "MILLIGRAM",
      "medicineFrequency": "ONCE_DAILY",
      "medicineTime": "BEFORE_MEAL"
    },
    {
      "medicineName": "Insulin",
      "medicineDosage": 20,
      "medicineUnit": "MILLILITER",
      "medicineFrequency": "THREE_TIMES_A_DAY",
      "medicineTime": "AFTER_MEAL"
    }
  ]
}
###

### Edit patient
PATCH {{patientPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "http://mockup.com/avatar.png",
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1990-01-01T00:00:00.000Z",
  "gender": "MALE",
  "medicalHistory": [
    {
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "allergy": {
    "medicine": "Penicillin",
    "food": null,
    "other": null
  },
  "familyHistory": [
    {
      "relationship": "Father",
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "relationship": "Mother",
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "heightValueCm": 180,
  "medicinceUsage": [
    {
      "medicineName": "Aspirin",
      "medicineDosage": 100,
      "medicineUnit": "MILLIGRAM",
      "medicineFrequency": "ONCE_DAILY",
      "medicineTime": "BEFORE_MEAL"
    },
    {
      "medicineName": "Insulin",
      "medicineDosage": 20,
      "medicineUnit": "MILLILITER",
      "medicineFrequency": "THREE_TIMES_A_DAY",
      "medicineTime": "AFTER_MEAL"
    }
  ]
}
###

@doctorPath={{hostname}}/api/doctors

### Register new doctor
POST {{doctorPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "",
  "firstName": "doctor2",
  "lastName": "doctor2",
  "gender": "FEMALE",
  "aboutMe": "I am a highly skilled doctor with over 10 years of experience in treating various illnesses.",
  "languagesSpoken": ["English", "Spanish", "French"],
  "specialties": ["Cardiology", "Oncology", "Neurology"],
  "careerStartDate": "2010-01-01T00:00:00.000Z",
  "officePracticalLocation": {
    "line1": "123 Main St.",
    "line2": "Suite 200",
    "city": "Los Angeles",
    "stateProvince": "California",
    "postalCode": "90001",
    "country": "United States",
    "countryCode": "US"
  },
  "education": ["Doctor of Medicine, University of California, Los Angeles"],
  "awards": ["Best Doctor Award 2015"],
  "affiliations": ["American Medical Association"]
}

###

### edit new doctor
PATCH {{doctorPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "https://example.com/avatar.png",
  "firstName": "John",
  "lastName": "Doe",
  "gender": "FEMALE",
  "aboutMe": "I am a highly skilled doctor with over 10 years of experience in treating various illnesses.",
  "languagesSpoken": ["English", "Spanish", "French"],
  "specialties": ["Cardiology", "Oncology", "Neurology"],
  "careerStartDate": "2010-01-01T00:00:00.000Z",
  "officePracticalLocation": {
    "line1": "123 Main St.",
    "line2": "Suite 200",
    "city": "Los Angeles",
    "stateProvince": "California",
    "postalCode": "90001",
    "country": "United States",
    "countryCode": "US"
  },
  "education": ["Doctor of Medicine, University of California, Los Angeles"],
  "awards": ["Best Doctor Award 2015"],
  "affiliations": ["American Medical Association"]
}
###