@hostname = http://localhost:10000
@usersPath = {{hostname}}/api/users

### Register new user
POST {{usersPath}}
Content-Type: application/json

{
  "displayName":"Tina",
  "email": "Tina@gmail.com",
  "password": "Tina",
  "role": "DOCTOR"
}
###

### user login
# @name login
POST {{usersPath}}/login
Content-Type: application/json

{
  "email": "tim@gmail.com",
  "password": "tim"
}
###
@accessToken = Bearer {{login.response.body.token}}

### get user account
GET {{usersPath}}/account
Authorization: {{accessToken}}
Content-Type: application/json
###

### edit user account
PATCH {{usersPath}}/account
Authorization: {{accessToken}}
Content-Type: application/json

{
  "displayName": "tim2",
  "password": "tim2"
}
###

@patientPath = {{hostname}}/api/patients

### Register new patient
POST {{patientPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": null,
  "firstName": "Tim",
  "lastName": "Wang",
  "birthDate": "1995-12-31T00:00:00.000Z",
  "gender": "MALE",
  "medicalHistory": [
    {
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "allergy": {
    "medicine": "Penicillin",
    "food": null,
    "other": null
  },
  "familyHistory": [
    {
      "relationship": "Father",
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "relationship": "Mother",
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "heightValueCm": 180,
  "medicinceUsage": [
    {
      "medicineName": "Aspirin",
      "medicineDosage": 100,
      "medicineUnit": "MILLIGRAM",
      "medicineFrequency": "ONCE_DAILY",
      "medicineTime": "BEFORE_MEAL"
    },
    {
      "medicineName": "Insulin",
      "medicineDosage": 20,
      "medicineUnit": "MILLILITER",
      "medicineFrequency": "THREE_TIMES_A_DAY",
      "medicineTime": "AFTER_MEAL"
    }
  ]
}
###

### Edit patient profile
PATCH {{patientPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "http://mockup.com/avatar.png",
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1990-01-01T00:00:00.000Z",
  "gender": "MALE",
  "medicalHistory": [
    {
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "allergy": {
    "medicine": "Penicillin",
    "food": null,
    "other": null
  },
  "familyHistory": [
    {
      "relationship": "Father",
      "diagnosis": "HYPERTENSION",
      "diagnosisDetails": "High blood pressure"
    },
    {
      "relationship": "Mother",
      "diagnosis": "DIABETES",
      "diagnosisDetails": "Type 2 diabetes"
    }
  ],
  "heightValueCm": 180,
  "medicinceUsage": [
    {
      "medicineName": "Aspirin",
      "medicineDosage": 100,
      "medicineUnit": "MILLIGRAM",
      "medicineFrequency": "ONCE_DAILY",
      "medicineTime": "BEFORE_MEAL"
    },
    {
      "medicineName": "Insulin",
      "medicineDosage": 20,
      "medicineUnit": "MILLILITER",
      "medicineFrequency": "THREE_TIMES_A_DAY",
      "medicineTime": "AFTER_MEAL"
    }
  ]
}
###

### get patient profile
GET {{patientPath}}/profile?targetPatientId=df5ff2e5-9d76-42ca-acfb-688267229369
Authorization: {{accessToken}}
Content-Type: application/json
###


@doctorPath={{hostname}}/api/doctors

### Register new doctor
POST {{doctorPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "null",
  "firstName": "Amy",
  "lastName": "Chen",
  "gender": "FEMALE",
  "aboutMe": "I am a highly skilled doctor with over 10 years of experience in treating various illnesses.",
  "languagesSpoken": ["English", "Spanish", "French"],
  "specialties": ["INTERNAL_MEDICINE"],
  "careerStartDate": "2010-01-01T00:00:00.000Z",
  "officePracticalLocation": {
    "line1": "123 Main St.",
    "line2": "Suite 200",
    "city": "Los Angeles",
    "stateProvince": "California",
    "postalCode": "90001",
    "country": "United States",
    "countryCode": "US"
  },
  "education": ["Doctor of Medicine, University of California, Los Angeles"],
  "awards": ["Best Doctor Award 2015"],
  "affiliations": ["American Medical Association"]
}

###

### edit doctor profile
PATCH {{doctorPath}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

{
  "avatar": "https://example.com/avatar.png",
  "firstName": "Eric",
  "lastName": "Chen",
  "gender": "MALE",
  "aboutMe": "I am a highly skilled doctor with over 10 years of experience in treating various illnesses.",
  "languagesSpoken": ["English", "Spanish", "French"],
  "specialties": ["INTERNAL_MEDICINE"],
  "careerStartDate": "2010-01-01T00:00:00.000Z",
  "officePracticalLocation": {
    "line1": "123 Main St.",
    "line2": "Suite 200",
    "city": "Los Angeles",
    "stateProvince": "California",
    "postalCode": "90001",
    "country": "United States",
    "countryCode": "US"
  },
  "education": ["Doctor of Medicine, University of California, Los Angeles"],
  "awards": ["Best Doctor Award 2015"],
  "affiliations": ["American Medical Association"]
}
###

### get a doctor profile
@Id=1844558f-ed47-46b9-83c8-5616599cc150
GET {{doctorPath}}/{{Id}}/profile
Authorization: {{accessToken}}
Content-Type: application/json

### get a doctor statistic
@doctorId=1fc5d738-43f9-4a77-8e1d-ab4ea15b29e3
GET {{doctorPath}}/{{doctorId}}/statistic
Authorization: {{accessToken}}
Content-Type: application/json

### get doctor list
GET {{doctorPath}}?limit=3&page=1&specialties=INTERNAL_MEDICINE
Authorization: {{accessToken}}
Content-Type: application/json